In [1]:
fc_pth = r'D:\projects\business-analyst-python-api-examples\data\raw\raw.gdb\pdx_coffee_study_areas_3min'

In [2]:
from arcgis.gis import GIS

In [4]:
gis_pro = GIS('pro')
gis_agol = GIS(profile='ba')

In [5]:
from arcgis.geoenrichment import get_countries, Country

In [9]:
get_countries(gis_pro)

  iso2 iso3           name  vintage     country_id        data_source_id
0   CA  CAN         Canada     2021  CAN_ESRI_2021  LOCAL;;CAN_ESRI_2021
1   US  USA  United States     2020  USA_ESRI_2020  LOCAL;;USA_ESRI_2020
2   US  USA  United States     2022  USA_ESRI_2022  LOCAL;;USA_ESRI_2022

In [10]:
usa = Country('usa', gis=gis_pro)

usa

In [11]:
ev = usa.enrich_variables

ev

,name,alias,data_collection,enrich_name,enrich_field_name
0,THHBASE,2022 Tapestry Household Base,BabyProductsToysGames,BabyProductsToysGames.THHBASE,BabyProductsToysGames_THHBASE
1,TADULTBASE,2022 Tapestry Adult Pop Base,BabyProductsToysGames,BabyProductsToysGames.TADULTBASE,BabyProductsToysGames_TADULTBASE
2,MP03017h_B,2022 HH Owns Any Baby Furniture or Equipment,BabyProductsToysGames,BabyProductsToysGames.MP03017h_B,BabyProductsToysGames_MP03017h_B
3,MP03017h_I,2022 Index: HH Owns Any Baby Furniture or Equi...,BabyProductsToysGames,BabyProductsToysGames.MP03017h_I,BabyProductsToysGames_MP03017h_I
4,MP03018h_B,2022 HH Bought Baby Furniture or Equipment/6 Mo,BabyProductsToysGames,BabyProductsToysGames.MP03018h_B,BabyProductsToysGames_MP03018h_B
...,...,...,...,...,...
18863,MOEMEDYRMV,2020 Median Year Householder Moved In MOE (ACS...,yearmovedin,yearmovedin.MOEMEDYRMV,yearmovedin_MOEMEDYRMV
18864,RELMEDYRMV,2020 Median Year Householder Moved In REL (ACS...,yearmovedin,yearmovedin.RELMEDYRMV,yearmovedin_RELMEDYRMV
18865,ACSOWNER,2020 Owner Households (ACS 5-Yr),yearmovedin,yearmovedin.ACSOWNER,yearmovedin_ACSOWNER
18866,MOEOWNER,2020 Owner Households MOE (ACS 5-Yr),yearmovedin,yearmovedin.MOEOWNER,yearmovedin_MOEOWNER
18867,RELOWNER,2020 Owner Households REL (ACS 5-Yr),yearmovedin,yearmovedin.RELOWNER,yearmovedin_RELOWNER

In [14]:
kv = ev[
    (ev.name.str.lower().str.contains('cy'))
    & (ev.data_collection.str.lower().str.contains('key'))
].reset_index(drop=True)

kv

,name,alias,data_collection,enrich_name,enrich_field_name
0,TOTPOP_CY,2022 Total Population,KeyUSFacts,KeyUSFacts.TOTPOP_CY,KeyUSFacts_TOTPOP_CY
1,GQPOP_CY,2022 Group Quarters Population,KeyUSFacts,KeyUSFacts.GQPOP_CY,KeyUSFacts_GQPOP_CY
2,DIVINDX_CY,2022 Diversity Index,KeyUSFacts,KeyUSFacts.DIVINDX_CY,KeyUSFacts_DIVINDX_CY
3,TOTHH_CY,2022 Total Households,KeyUSFacts,KeyUSFacts.TOTHH_CY,KeyUSFacts_TOTHH_CY
4,AVGHHSZ_CY,2022 Average Household Size,KeyUSFacts,KeyUSFacts.AVGHHSZ_CY,KeyUSFacts_AVGHHSZ_CY
5,MEDHINC_CY,2022 Median Household Income,KeyUSFacts,KeyUSFacts.MEDHINC_CY,KeyUSFacts_MEDHINC_CY
6,AVGHINC_CY,2022 Average Household Income,KeyUSFacts,KeyUSFacts.AVGHINC_CY,KeyUSFacts_AVGHINC_CY
7,PCI_CY,2022 Per Capita Income,KeyUSFacts,KeyUSFacts.PCI_CY,KeyUSFacts_PCI_CY
8,TOTHU_CY,2022 Total Housing Units,KeyUSFacts,KeyUSFacts.TOTHU_CY,KeyUSFacts_TOTHU_CY
9,OWNER_CY,2022 Owner Occupied HUs,KeyUSFacts,KeyUSFacts.OWNER_CY,KeyUSFacts_OWNER_CY
10,RENTER_CY,2022 Renter Occupied HUs,KeyUSFacts,KeyUSFacts.RENTER_CY,KeyUSFacts_RENTER_CY
11,VACANT_CY,2022 Vacant Housing Units,KeyUSFacts,KeyUSFacts.VACANT_CY,KeyUSFacts_VACANT_CY
12,MEDVAL_CY,2022 Median Home Value,KeyUSFacts,KeyUSFacts.MEDVAL_CY,KeyUSFacts_MEDVAL_CY
13,AVGVAL_CY,2022 Average Home Value,KeyUSFacts,KeyUSFacts.AVGVAL_CY,KeyUSFacts_AVGVAL_CY
14,POPGRWCYFY,2022-2027 Growth Rate: Population,KeyUSFacts,KeyUSFacts.POPGRWCYFY,KeyUSFacts_POPGRWCYFY
15,HHGRWCYFY,2022-2027 Growth Rate: Households,KeyUSFacts,KeyUSFacts.HHGRWCYFY,KeyUSFacts_HHGRWCYFY
16,FAMGRWCYFY,2022-2027 Growth Rate: Families,KeyUSFacts,KeyUSFacts.FAMGRWCYFY,KeyUSFacts_FAMGRWCYFY
17,MHIGRWCYFY,2022-2027 Growth Rate: Median HH Inc,KeyUSFacts,KeyUSFacts.MHIGRWCYFY,KeyUSFacts_MHIGRWCYFY
18,PCIGRWCYFY,2022-2027 Growth Rate: Per Capita Inc,KeyUSFacts,KeyUSFacts.PCIGRWCYFY,KeyUSFacts_PCIGRWCYFY
19,DPOP_CY,2022 Total Daytime Population,KeyUSFacts,KeyUSFacts.DPOP_CY,KeyUSFacts_DPOP_CY
20,DPOPWRK_CY,2022 Daytime Pop: Workers,KeyUSFacts,KeyUSFacts.DPOPWRK_CY,KeyUSFacts_DPOPWRK_CY
21,DPOPRES_CY,2022 Daytime Pop: Residents,KeyUSFacts,KeyUSFacts.DPOPRES_CY,KeyUSFacts_DPOPRES_CY

In [15]:
from arcgis.features import GeoAccessor

In [16]:
sa_df = GeoAccessor.from_featureclass(fc_pth)

sa_df.info()
sa_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OBJECTID    650 non-null    int64
 1   AREA_ID     650 non-null    object
 2   AREA_DESC   650 non-null    object
 3   AREA_DESC2  650 non-null    object
 4   AREA_DESC3  650 non-null    object
 5   RING        650 non-null    int64
 6   RING_DEFN   650 non-null    object
 7   STORE_LAT   650 non-null    float64
 8   STORE_LON   650 non-null    float64
 9   LOCNUM      650 non-null    object
 10  CONAME      650 non-null    object
 11  STREET      650 non-null    object
 12  CITY        650 non-null    object
 13  STATE       650 non-null    object
 14  STATE_NAME  650 non-null    object
 15  ZIP         650 non-null    object
 16  ZIP4        650 non-null    object
 17  NAICS       650 non-null    object
 18  SIC         650 non-null    object
 19  SALESVOL    650 non-null    int64
 20  HDBRCH      650 non-null    object
 21  ULTNUM      650 non-null    object
 22  PUBPRV      650 non-null    object
 23  EMPNUM      650 non-null    int64
 24  FRNCOD      650 non-null    object
 25  ISCODE      650 non-null    object
 26  SQFTCODE    650 non-null    object
 27  LOC_NAME    650 non-null    object
 28  STATUS      650 non-null    object
 29  SCORE       650 non-null    float64
 30  SOURCE      650 non-null    object
 31  REC_TYPE    650 non-null    int64
 32  SHAPE       650 non-null    geometry
dtypes: float64(3), geometry(1), int64(5), object(24)
memory usage: 167.7+ KB

,OBJECTID,AREA_ID,AREA_DESC,AREA_DESC2,AREA_DESC3,RING,RING_DEFN,STORE_LAT,STORE_LON,LOCNUM,...,EMPNUM,FRNCOD,ISCODE,SQFTCODE,LOC_NAME,STATUS,SCORE,SOURCE,REC_TYPE,SHAPE
0,1,1_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1,3,45.410013,-122.720535,105550909,...,16,,,2,PointAddress,M,100.000000,Data Axle,0,"{""rings"": [[[-13659712.491841972, 5689050.6789..."
1,2,2_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1,3,45.555732,-122.919026,105633002,...,75,,,3,PointAddress,M,100.000000,Data Axle,0,"{""rings"": [[[-13683812.381583042, 5712092.0429..."
2,3,3_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1,3,45.525285,-122.677731,105759815,...,2,,,1,PointAddress,M,100.000000,Data Axle,0,"{""rings"": [[[-13655812.509662066, 5706201.2159..."
3,4,4_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1,3,45.417519,-122.633325,177692910,...,14,4,,2,PointAddress,M,99.890625,Data Axle,0,"{""rings"": [[[-13651962.527299367, 5690511.2941..."
4,5,5_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1,3,45.534159,-122.538366,180308389,...,2,,,1,PointAddress,M,100.000000,Data Axle,0,"{""rings"": [[[-13640787.578395057, 5708949.7851..."

In [17]:
enrich_df = usa.enrich(sa_df, enrich_variables=kv)

enrich_df.info()
enrich_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 56 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   area_id             650 non-null    object
 1   area_desc           650 non-null    object
 2   area_desc2          650 non-null    object
 3   area_desc3          650 non-null    object
 4   ring                650 non-null    float64
 5   ring_defn           650 non-null    object
 6   store_lat           650 non-null    float64
 7   store_lon           650 non-null    float64
 8   locnum              650 non-null    object
 9   coname              650 non-null    object
 10  street              650 non-null    object
 11  city                650 non-null    object
 12  state               650 non-null    object
 13  state_name          650 non-null    object
 14  zip                 650 non-null    object
 15  zip4                650 non-null    object
 16  naics               650 non-null    object
 17  sic                 650 non-null    object
 18  salesvol            650 non-null    float64
 19  hdbrch              650 non-null    object
 20  ultnum              650 non-null    object
 21  pubprv              650 non-null    object
 22  empnum              650 non-null    float64
 23  frncod              650 non-null    object
 24  iscode              650 non-null    object
 25  sqftcode            650 non-null    object
 26  loc_name            650 non-null    object
 27  status              650 non-null    object
 28  score               650 non-null    float64
 29  source              650 non-null    object
 30  rec_type            650 non-null    float64
 31  has_data            650 non-null    int32
 32  aggregation_method  650 non-null    object
 33  totpop_cy           650 non-null    float64
 34  gqpop_cy            650 non-null    float64
 35  divindx_cy          650 non-null    float64
 36  tothh_cy            650 non-null    float64
 37  avghhsz_cy          650 non-null    float64
 38  medhinc_cy          650 non-null    float64
 39  avghinc_cy          650 non-null    float64
 40  pci_cy              650 non-null    float64
 41  tothu_cy            650 non-null    float64
 42  owner_cy            650 non-null    float64
 43  renter_cy           650 non-null    float64
 44  vacant_cy           650 non-null    float64
 45  medval_cy           650 non-null    float64
 46  avgval_cy           650 non-null    float64
 47  popgrwcyfy          650 non-null    float64
 48  hhgrwcyfy           650 non-null    float64
 49  famgrwcyfy          650 non-null    float64
 50  mhigrwcyfy          650 non-null    float64
 51  pcigrwcyfy          650 non-null    float64
 52  dpop_cy             650 non-null    float64
 53  dpopwrk_cy          650 non-null    float64
 54  dpopres_cy          650 non-null    float64
 55  SHAPE               650 non-null    geometry
dtypes: float64(29), geometry(1), int32(1), object(25)
memory usage: 282.0+ KB

,area_id,area_desc,area_desc2,area_desc3,ring,ring_defn,store_lat,store_lon,locnum,coname,...,avgval_cy,popgrwcyfy,hhgrwcyfy,famgrwcyfy,mhigrwcyfy,pcigrwcyfy,dpop_cy,dpopwrk_cy,dpopres_cy,SHAPE
0,1_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1.0,3,45.410013,-122.720535,105550909,RICCARDO'S RISTORANTE,...,713998.0,1.02,0.91,0.77,3.40,2.48,9885.0,7269.0,2616.0,"{""rings"": [[[-122.70728508062291, 45.427343047..."
1,2_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1.0,3,45.555732,-122.919026,105633002,LONGBOTTOM COFFEE & TEA,...,485714.0,-0.52,0.00,0.00,1.42,3.76,1868.0,1851.0,17.0,"{""rings"": [[[-122.92377807415231, 45.572420302..."
2,3_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1.0,3,45.525285,-122.677731,105759815,JOHN'S CAFE,...,675513.0,0.76,0.77,0.81,9.42,4.19,35674.0,30605.0,5069.0,"{""rings"": [[[-122.6722509453407, 45.5353649659..."
3,4_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1.0,3,45.417519,-122.633325,177692910,STARBUCKS,...,434913.0,0.07,0.05,-0.05,2.76,3.69,5306.0,2665.0,2641.0,"{""rings"": [[[-122.6376659650056, 45.4365507371..."
4,5_1,3 Minutes,Driving Time: 3 Minute Distance,Driving Time: 3 Minute Distance,1.0,3,45.534159,-122.538366,180308389,PERFECT CUP ESPRESSO,...,402622.0,-0.25,-0.37,-0.41,4.24,3.74,11804.0,5107.0,6697.0,"{""rings"": [[[-122.53727969104438, 45.552657456..."