In [1]:
from arcgis.features import GeoAccessor
from arcgis.gis import GIS

from arcgis.geoenrichment import get_countries, Country

In [2]:
sa_pth = r'D:\projects\business-analyst-python-api-examples\data\raw\raw.gdb\pdx_coffee_study_areas_3min_small'

In [3]:
df = GeoAccessor.from_featureclass(sa_pth)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OBJECTID  5 non-null      int64
 1   locnum    5 non-null      object
 2   SHAPE     5 non-null      geometry
dtypes: geometry(1), int64(1), object(1)
memory usage: 248.0+ bytes

   OBJECTID     locnum                                              SHAPE
0         1  395959703  {"rings": [[[-13633937.6097, 5701669.707400002...
1         2  632063731  {"rings": [[[-13634112.6089, 5707200.597800001...
2         3  740967835  {"rings": [[[-13623737.656399999, 5701455.6771...
3         4  749646031  {"rings": [[[-13629262.631099999, 5706593.8169...
4         5  750786722  {"rings": [[[-13625787.647, 5708271.488200001]...

In [4]:
gis = GIS('pro')

In [5]:
get_countries(gis)

  iso2 iso3           name  vintage     country_id        data_source_id
0   CA  CAN         Canada     2021  CAN_ESRI_2021  LOCAL;;CAN_ESRI_2021
1   US  USA  United States     2020  USA_ESRI_2020  LOCAL;;USA_ESRI_2020
2   US  USA  United States     2022  USA_ESRI_2022  LOCAL;;USA_ESRI_2022

In [6]:
usa = Country('usa', gis=gis)

usa

In [7]:
ev = usa.enrich_variables

ev

             name  ...                 enrich_field_name
0         THHBASE  ...     BabyProductsToysGames_THHBASE
1      TADULTBASE  ...  BabyProductsToysGames_TADULTBASE
2      MP03017h_B  ...  BabyProductsToysGames_MP03017h_B
3      MP03017h_I  ...  BabyProductsToysGames_MP03017h_I
4      MP03018h_B  ...  BabyProductsToysGames_MP03018h_B
...           ...  ...                               ...
18863  MOEMEDYRMV  ...            yearmovedin_MOEMEDYRMV
18864  RELMEDYRMV  ...            yearmovedin_RELMEDYRMV
18865    ACSOWNER  ...              yearmovedin_ACSOWNER
18866    MOEOWNER  ...              yearmovedin_MOEOWNER
18867    RELOWNER  ...              yearmovedin_RELOWNER

[18868 rows x 5 columns]

In [8]:
kv = ev[
    (ev.name.str.lower().str.contains('cy'))
    & (ev.data_collection.str.lower().str.startswith('key'))
].reset_index(drop=True)

kv

          name  ...      enrich_field_name
0    TOTPOP_CY  ...   KeyUSFacts_TOTPOP_CY
1     GQPOP_CY  ...    KeyUSFacts_GQPOP_CY
2   DIVINDX_CY  ...  KeyUSFacts_DIVINDX_CY
3     TOTHH_CY  ...    KeyUSFacts_TOTHH_CY
4   AVGHHSZ_CY  ...  KeyUSFacts_AVGHHSZ_CY
5   MEDHINC_CY  ...  KeyUSFacts_MEDHINC_CY
6   AVGHINC_CY  ...  KeyUSFacts_AVGHINC_CY
7       PCI_CY  ...      KeyUSFacts_PCI_CY
8     TOTHU_CY  ...    KeyUSFacts_TOTHU_CY
9     OWNER_CY  ...    KeyUSFacts_OWNER_CY
10   RENTER_CY  ...   KeyUSFacts_RENTER_CY
11   VACANT_CY  ...   KeyUSFacts_VACANT_CY
12   MEDVAL_CY  ...   KeyUSFacts_MEDVAL_CY
13   AVGVAL_CY  ...   KeyUSFacts_AVGVAL_CY
14  POPGRWCYFY  ...  KeyUSFacts_POPGRWCYFY
15   HHGRWCYFY  ...   KeyUSFacts_HHGRWCYFY
16  FAMGRWCYFY  ...  KeyUSFacts_FAMGRWCYFY
17  MHIGRWCYFY  ...  KeyUSFacts_MHIGRWCYFY
18  PCIGRWCYFY  ...  KeyUSFacts_PCIGRWCYFY
19     DPOP_CY  ...     KeyUSFacts_DPOP_CY
20  DPOPWRK_CY  ...  KeyUSFacts_DPOPWRK_CY
21  DPOPRES_CY  ...  KeyUSFacts_DPOPRES_CY

[22 rows x 5 columns]

In [9]:
e_df = usa.enrich(df, kv)

e_df.info()
e_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   locnum              5 non-null      object
 1   has_data            5 non-null      int32
 2   aggregation_method  5 non-null      object
 3   totpop_cy           5 non-null      float64
 4   gqpop_cy            5 non-null      float64
 5   divindx_cy          5 non-null      float64
 6   tothh_cy            5 non-null      float64
 7   avghhsz_cy          5 non-null      float64
 8   medhinc_cy          5 non-null      float64
 9   avghinc_cy          5 non-null      float64
 10  pci_cy              5 non-null      float64
 11  tothu_cy            5 non-null      float64
 12  owner_cy            5 non-null      float64
 13  renter_cy           5 non-null      float64
 14  vacant_cy           5 non-null      float64
 15  medval_cy           5 non-null      float64
 16  avgval_cy           5 non-null      float64
 17  popgrwcyfy          5 non-null      float64
 18  hhgrwcyfy           5 non-null      float64
 19  famgrwcyfy          5 non-null      float64
 20  mhigrwcyfy          5 non-null      float64
 21  pcigrwcyfy          5 non-null      float64
 22  dpop_cy             5 non-null      float64
 23  dpopwrk_cy          5 non-null      float64
 24  dpopres_cy          5 non-null      float64
 25  SHAPE               5 non-null      geometry
dtypes: float64(22), geometry(1), int32(1), object(2)
memory usage: 1.1+ KB

      locnum  ...                                              SHAPE
0  395959703  ...  {"rings": [[[-122.47574537525485, 45.506843586...
1  632063731  ...  {"rings": [[[-122.47731741981552, 45.541653144...
2  740967835  ...  {"rings": [[[-122.38411763578789, 45.505496118...
3  749646031  ...  {"rings": [[[-122.43374932796173, 45.537835321...
4  750786722  ...  {"rings": [[[-122.40253301467071, 45.548390478...

[5 rows x 26 columns]